---
eureka:
  client:
    service-url:
      { defaultZone: "http://localhost:8010/eureka/" }

---
spring:
  profiles:
    active: subject-service
words: I,You,He,She,It

---
spring:
  profiles:
    active: verb-service
words: ran,knew,had,saw,bought

---
spring:
  profiles:
    active: article-service
words: a,the

---
spring:
  profiles:
    active: adjective-service
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles:
  active: noun-service
words: boat,book,vote,seat,backpack,partition,groundhog
