---
eureka:
  client:
    service-url:
      { defaultZone: "http://localhost:8010/eureka/" }

---
#spring:
 # profiles:
 #   active: subject-service
spring.profiles: subject-service 
words: I,You,He,She,It

---
spring.profiles: verb-service
words: ran,knew,had,saw,bought

---
spring.profiles: article-service
words: a,the

---
spring.profiles: adjective-service
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring.profiles: noun-service
words: boat,book,vote,seat,backpack,partition,groundhog
